package io.github.vinaooo.vinkit.designsystem

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.github.vinaooo.vinkit.core.ThemeColor

/** [color]'s scheme, light or [dark]. */
fun paletteScheme(color: ThemeColor, dark: Boolean): ColorScheme {
    val (light, darkScheme) = when (color) {
        ThemeColor.GREEN -> GreenColors.light to GreenColors.dark
        ThemeColor.TEAL -> TealColors.light to TealColors.dark
        ThemeColor.BLUE -> BlueColors.light to BlueColors.dark
        ThemeColor.INDIGO -> IndigoColors.light to IndigoColors.dark
        ThemeColor.PURPLE -> PurpleColors.light to PurpleColors.dark
        ThemeColor.PINK -> PinkColors.light to PinkColors.dark
        ThemeColor.RED -> RedColors.light to RedColors.dark
        ThemeColor.ORANGE -> OrangeColors.light to OrangeColors.dark
    }
    return if (dark) darkScheme else light
}

// Generated once with Google's material-color-utilities (SchemeTonalSpot, 2021 spec, as Android's dynamic color), and
// committed, so no color library ships. Seeds: Teal #00897B, Blue #1E88E5, Indigo #3F51B5,
// Purple #8E24AA, Pink #D81B60, Red #E53935, Orange #FB8C00. Green is Solo's brand palette.

internal object TealColors {
    val light = lightColorScheme(
        primary = Color(0xFF006B5F),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF9EF2E3),
        onPrimaryContainer = Color(0xFF005048),
        inversePrimary = Color(0xFF82D5C7),
        secondary = Color(0xFF4A635E),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFCCE8E2),
        onSecondaryContainer = Color(0xFF334B47),
        tertiary = Color(0xFF456179),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFCBE6FF),
        onTertiaryContainer = Color(0xFF2D4A60),
        background = Color(0xFFF4FBF8),
        onBackground = Color(0xFF161D1B),
        surface = Color(0xFFF4FBF8),
        onSurface = Color(0xFF161D1B),
        surfaceVariant = Color(0xFFDAE5E1),
        onSurfaceVariant = Color(0xFF3F4946),
        inverseSurface = Color(0xFF2B3230),
        inverseOnSurface = Color(0xFFECF2EF),
        outline = Color(0xFF6F7976),
        outlineVariant = Color(0xFFBEC9C5),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFEFF5F2),
        surfaceContainer = Color(0xFFE9EFEC),
        surfaceContainerHigh = Color(0xFFE3EAE7),
        surfaceContainerHighest = Color(0xFFDDE4E1),
    )

    val dark = darkColorScheme(
        primary = Color(0xFF82D5C7),
        onPrimary = Color(0xFF003731),
        primaryContainer = Color(0xFF005048),
        onPrimaryContainer = Color(0xFF9EF2E3),
        inversePrimary = Color(0xFF006B5F),
        secondary = Color(0xFFB1CCC6),
        onSecondary = Color(0xFF1C3531),
        secondaryContainer = Color(0xFF334B47),
        onSecondaryContainer = Color(0xFFCCE8E2),
        tertiary = Color(0xFFADCAE5),
        onTertiary = Color(0xFF143349),
        tertiaryContainer = Color(0xFF2D4A60),
        onTertiaryContainer = Color(0xFFCBE6FF),
        background = Color(0xFF0E1513),
        onBackground = Color(0xFFDDE4E1),
        surface = Color(0xFF0E1513),
        onSurface = Color(0xFFDDE4E1),
        surfaceVariant = Color(0xFF3F4946),
        onSurfaceVariant = Color(0xFFBEC9C5),
        inverseSurface = Color(0xFFDDE4E1),
        inverseOnSurface = Color(0xFF2B3230),
        outline = Color(0xFF899390),
        outlineVariant = Color(0xFF3F4946),
        surfaceContainerLowest = Color(0xFF090F0E),
        surfaceContainerLow = Color(0xFF161D1B),
        surfaceContainer = Color(0xFF1A211F),
        surfaceContainerHigh = Color(0xFF252B2A),
        surfaceContainerHighest = Color(0xFF303634),
    )
}

internal object BlueColors {
    val light = lightColorScheme(
        primary = Color(0xFF39608F),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD3E4FF),
        onPrimaryContainer = Color(0xFF1D4875),
        inversePrimary = Color(0xFFA3C9FE),
        secondary = Color(0xFF545F70),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD7E3F8),
        onSecondaryContainer = Color(0xFF3C4858),
        tertiary = Color(0xFF6C5677),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFF4D9FF),
        onTertiaryContainer = Color(0xFF533F5E),
        background = Color(0xFFF8F9FF),
        onBackground = Color(0xFF191C20),
        surface = Color(0xFFF8F9FF),
        onSurface = Color(0xFF191C20),
        surfaceVariant = Color(0xFFDFE2EB),
        onSurfaceVariant = Color(0xFF43474E),
        inverseSurface = Color(0xFF2E3035),
        inverseOnSurface = Color(0xFFEFF0F7),
        outline = Color(0xFF73777F),
        outlineVariant = Color(0xFFC3C6CF),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF2F3FA),
        surfaceContainer = Color(0xFFECEDF4),
        surfaceContainerHigh = Color(0xFFE7E8EE),
        surfaceContainerHighest = Color(0xFFE1E2E8),
    )

    val dark = darkColorScheme(
        primary = Color(0xFFA3C9FE),
        onPrimary = Color(0xFF00315B),
        primaryContainer = Color(0xFF1D4875),
        onPrimaryContainer = Color(0xFFD3E4FF),
        inversePrimary = Color(0xFF39608F),
        secondary = Color(0xFFBBC7DB),
        onSecondary = Color(0xFF263141),
        secondaryContainer = Color(0xFF3C4858),
        onSecondaryContainer = Color(0xFFD7E3F8),
        tertiary = Color(0xFFD8BDE3),
        onTertiary = Color(0xFF3C2947),
        tertiaryContainer = Color(0xFF533F5E),
        onTertiaryContainer = Color(0xFFF4D9FF),
        background = Color(0xFF111418),
        onBackground = Color(0xFFE1E2E8),
        surface = Color(0xFF111418),
        onSurface = Color(0xFFE1E2E8),
        surfaceVariant = Color(0xFF43474E),
        onSurfaceVariant = Color(0xFFC3C6CF),
        inverseSurface = Color(0xFFE1E2E8),
        inverseOnSurface = Color(0xFF2E3035),
        outline = Color(0xFF8D9199),
        outlineVariant = Color(0xFF43474E),
        surfaceContainerLowest = Color(0xFF0C0E13),
        surfaceContainerLow = Color(0xFF191C20),
        surfaceContainer = Color(0xFF1D2024),
        surfaceContainerHigh = Color(0xFF272A2F),
        surfaceContainerHighest = Color(0xFF32353A),
    )
}

internal object IndigoColors {
    val light = lightColorScheme(
        primary = Color(0xFF515B92),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFDEE0FF),
        onPrimaryContainer = Color(0xFF394379),
        inversePrimary = Color(0xFFBAC3FF),
        secondary = Color(0xFF5B5D72),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE0E1F9),
        onSecondaryContainer = Color(0xFF434659),
        tertiary = Color(0xFF77536D),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD7F1),
        onTertiaryContainer = Color(0xFF5D3C55),
        background = Color(0xFFFBF8FF),
        onBackground = Color(0xFF1B1B21),
        surface = Color(0xFFFBF8FF),
        onSurface = Color(0xFF1B1B21),
        surfaceVariant = Color(0xFFE3E1EC),
        onSurfaceVariant = Color(0xFF46464F),
        inverseSurface = Color(0xFF303036),
        inverseOnSurface = Color(0xFFF2EFF7),
        outline = Color(0xFF767680),
        outlineVariant = Color(0xFFC7C5D0),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF5F2FA),
        surfaceContainer = Color(0xFFEFEDF4),
        surfaceContainerHigh = Color(0xFFE9E7EF),
        surfaceContainerHighest = Color(0xFFE4E1E9),
    )

    val dark = darkColorScheme(
        primary = Color(0xFFBAC3FF),
        onPrimary = Color(0xFF222C61),
        primaryContainer = Color(0xFF394379),
        onPrimaryContainer = Color(0xFFDEE0FF),
        inversePrimary = Color(0xFF515B92),
        secondary = Color(0xFFC3C5DD),
        onSecondary = Color(0xFF2D2F42),
        secondaryContainer = Color(0xFF434659),
        onSecondaryContainer = Color(0xFFE0E1F9),
        tertiary = Color(0xFFE6BAD7),
        onTertiary = Color(0xFF44263D),
        tertiaryContainer = Color(0xFF5D3C55),
        onTertiaryContainer = Color(0xFFFFD7F1),
        background = Color(0xFF121318),
        onBackground = Color(0xFFE4E1E9),
        surface = Color(0xFF121318),
        onSurface = Color(0xFFE4E1E9),
        surfaceVariant = Color(0xFF46464F),
        onSurfaceVariant = Color(0xFFC7C5D0),
        inverseSurface = Color(0xFFE4E1E9),
        inverseOnSurface = Color(0xFF303036),
        outline = Color(0xFF90909A),
        outlineVariant = Color(0xFF46464F),
        surfaceContainerLowest = Color(0xFF0D0E13),
        surfaceContainerLow = Color(0xFF1B1B21),
        surfaceContainer = Color(0xFF1F1F25),
        surfaceContainerHigh = Color(0xFF29292F),
        surfaceContainerHighest = Color(0xFF34343A),
    )
}

internal object PurpleColors {
    val light = lightColorScheme(
        primary = Color(0xFF794F81),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFDD6FF),
        onPrimaryContainer = Color(0xFF603768),
        inversePrimary = Color(0xFFE8B5EF),
        secondary = Color(0xFF6A596C),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFF3DBF2),
        onSecondaryContainer = Color(0xFF524153),
        tertiary = Color(0xFF82524C),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDAD6),
        onTertiaryContainer = Color(0xFF673B36),
        background = Color(0xFFFFF7FB),
        onBackground = Color(0xFF1F1A1F),
        surface = Color(0xFFFFF7FB),
        onSurface = Color(0xFF1F1A1F),
        surfaceVariant = Color(0xFFECDFE9),
        onSurfaceVariant = Color(0xFF4C444C),
        inverseSurface = Color(0xFF342F34),
        inverseOnSurface = Color(0xFFF9EEF5),
        outline = Color(0xFF7E747D),
        outlineVariant = Color(0xFFCFC3CD),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFCF1F8),
        surfaceContainer = Color(0xFFF6EBF2),
        surfaceContainerHigh = Color(0xFFF0E5EC),
        surfaceContainerHighest = Color(0xFFEAE0E7),
    )

    val dark = darkColorScheme(
        primary = Color(0xFFE8B5EF),
        onPrimary = Color(0xFF472150),
        primaryContainer = Color(0xFF603768),
        onPrimaryContainer = Color(0xFFFDD6FF),
        inversePrimary = Color(0xFF794F81),
        secondary = Color(0xFFD6C0D6),
        onSecondary = Color(0xFF3A2B3C),
        secondaryContainer = Color(0xFF524153),
        onSecondaryContainer = Color(0xFFF3DBF2),
        tertiary = Color(0xFFF5B7B0),
        onTertiary = Color(0xFF4C2521),
        tertiaryContainer = Color(0xFF673B36),
        onTertiaryContainer = Color(0xFFFFDAD6),
        background = Color(0xFF171217),
        onBackground = Color(0xFFEAE0E7),
        surface = Color(0xFF171217),
        onSurface = Color(0xFFEAE0E7),
        surfaceVariant = Color(0xFF4C444C),
        onSurfaceVariant = Color(0xFFCFC3CD),
        inverseSurface = Color(0xFFEAE0E7),
        inverseOnSurface = Color(0xFF342F34),
        outline = Color(0xFF988E97),
        outlineVariant = Color(0xFF4C444C),
        surfaceContainerLowest = Color(0xFF110D11),
        surfaceContainerLow = Color(0xFF1F1A1F),
        surfaceContainer = Color(0xFF231E23),
        surfaceContainerHigh = Color(0xFF2E282E),
        surfaceContainerHighest = Color(0xFF393338),
    )
}

internal object PinkColors {
    val light = lightColorScheme(
        primary = Color(0xFF8E4958),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD9DE),
        onPrimaryContainer = Color(0xFF713341),
        inversePrimary = Color(0xFFFFB2BF),
        secondary = Color(0xFF75565B),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFD9DE),
        onSecondaryContainer = Color(0xFF5C3F44),
        tertiary = Color(0xFF7A5832),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDCBB),
        onTertiaryContainer = Color(0xFF5F401D),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF22191B),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF22191B),
        surfaceVariant = Color(0xFFF3DDE0),
        onSurfaceVariant = Color(0xFF524345),
        inverseSurface = Color(0xFF382E2F),
        inverseOnSurface = Color(0xFFFEEDEE),
        outline = Color(0xFF847375),
        outlineVariant = Color(0xFFD6C2C4),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF0F1),
        surfaceContainer = Color(0xFFFBEAEB),
        surfaceContainerHigh = Color(0xFFF5E4E6),
        surfaceContainerHighest = Color(0xFFF0DEE0),
    )

    val dark = darkColorScheme(
        primary = Color(0xFFFFB2BF),
        onPrimary = Color(0xFF561D2B),
        primaryContainer = Color(0xFF713341),
        onPrimaryContainer = Color(0xFFFFD9DE),
        inversePrimary = Color(0xFF8E4958),
        secondary = Color(0xFFE4BDC2),
        onSecondary = Color(0xFF43292E),
        secondaryContainer = Color(0xFF5C3F44),
        onSecondaryContainer = Color(0xFFFFD9DE),
        tertiary = Color(0xFFEBBE90),
        onTertiary = Color(0xFF462A08),
        tertiaryContainer = Color(0xFF5F401D),
        onTertiaryContainer = Color(0xFFFFDCBB),
        background = Color(0xFF191113),
        onBackground = Color(0xFFF0DEE0),
        surface = Color(0xFF191113),
        onSurface = Color(0xFFF0DEE0),
        surfaceVariant = Color(0xFF524345),
        onSurfaceVariant = Color(0xFFD6C2C4),
        inverseSurface = Color(0xFFF0DEE0),
        inverseOnSurface = Color(0xFF382E2F),
        outline = Color(0xFF9F8C8E),
        outlineVariant = Color(0xFF524345),
        surfaceContainerLowest = Color(0xFF140C0D),
        surfaceContainerLow = Color(0xFF22191B),
        surfaceContainer = Color(0xFF261D1F),
        surfaceContainerHigh = Color(0xFF312829),
        surfaceContainerHighest = Color(0xFF3C3234),
    )
}

internal object RedColors {
    val light = lightColorScheme(
        primary = Color(0xFF904A44),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDAD6),
        onPrimaryContainer = Color(0xFF73332E),
        inversePrimary = Color(0xFFFFB4AC),
        secondary = Color(0xFF775653),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDAD6),
        onSecondaryContainer = Color(0xFF5D3F3C),
        tertiary = Color(0xFF715B2E),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFEDFA6),
        onTertiaryContainer = Color(0xFF584419),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF231918),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF231918),
        surfaceVariant = Color(0xFFF5DDDB),
        onSurfaceVariant = Color(0xFF534341),
        inverseSurface = Color(0xFF392E2D),
        inverseOnSurface = Color(0xFFFFEDEA),
        outline = Color(0xFF857371),
        outlineVariant = Color(0xFFD8C2BF),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF0EE),
        surfaceContainer = Color(0xFFFCEAE7),
        surfaceContainerHigh = Color(0xFFF6E4E2),
        surfaceContainerHighest = Color(0xFFF1DEDC),
    )

    val dark = darkColorScheme(
        primary = Color(0xFFFFB4AC),
        onPrimary = Color(0xFF561E1A),
        primaryContainer = Color(0xFF73332E),
        onPrimaryContainer = Color(0xFFFFDAD6),
        inversePrimary = Color(0xFF904A44),
        secondary = Color(0xFFE7BDB8),
        onSecondary = Color(0xFF442927),
        secondaryContainer = Color(0xFF5D3F3C),
        onSecondaryContainer = Color(0xFFFFDAD6),
        tertiary = Color(0xFFE0C38C),
        onTertiary = Color(0xFF3F2E04),
        tertiaryContainer = Color(0xFF584419),
        onTertiaryContainer = Color(0xFFFEDFA6),
        background = Color(0xFF1A1110),
        onBackground = Color(0xFFF1DEDC),
        surface = Color(0xFF1A1110),
        onSurface = Color(0xFFF1DEDC),
        surfaceVariant = Color(0xFF534341),
        onSurfaceVariant = Color(0xFFD8C2BF),
        inverseSurface = Color(0xFFF1DEDC),
        inverseOnSurface = Color(0xFF392E2D),
        outline = Color(0xFFA08C8A),
        outlineVariant = Color(0xFF534341),
        surfaceContainerLowest = Color(0xFF140C0B),
        surfaceContainerLow = Color(0xFF231918),
        surfaceContainer = Color(0xFF271D1C),
        surfaceContainerHigh = Color(0xFF322826),
        surfaceContainerHighest = Color(0xFF3D3231),
    )
}

internal object OrangeColors {
    val light = lightColorScheme(
        primary = Color(0xFF88511D),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDCC2),
        onPrimaryContainer = Color(0xFF6B3A05),
        inversePrimary = Color(0xFFFFB77B),
        secondary = Color(0xFF745944),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDCC2),
        onSecondaryContainer = Color(0xFF5A422E),
        tertiary = Color(0xFF5B6237),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFE0E7B1),
        onTertiaryContainer = Color(0xFF444A22),
        background = Color(0xFFFFF8F5),
        onBackground = Color(0xFF221A14),
        surface = Color(0xFFFFF8F5),
        onSurface = Color(0xFF221A14),
        surfaceVariant = Color(0xFFF3DFD1),
        onSurfaceVariant = Color(0xFF51443B),
        inverseSurface = Color(0xFF382F28),
        inverseOnSurface = Color(0xFFFEEEE4),
        outline = Color(0xFF847469),
        outlineVariant = Color(0xFFD6C3B6),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF1E8),
        surfaceContainer = Color(0xFFFBEBE1),
        surfaceContainerHigh = Color(0xFFF5E5DB),
        surfaceContainerHighest = Color(0xFFEFE0D6),
    )

    val dark = darkColorScheme(
        primary = Color(0xFFFFB77B),
        onPrimary = Color(0xFF4C2700),
        primaryContainer = Color(0xFF6B3A05),
        onPrimaryContainer = Color(0xFFFFDCC2),
        inversePrimary = Color(0xFF88511D),
        secondary = Color(0xFFE3C0A5),
        onSecondary = Color(0xFF412C19),
        secondaryContainer = Color(0xFF5A422E),
        onSecondaryContainer = Color(0xFFFFDCC2),
        tertiary = Color(0xFFC4CB97),
        onTertiary = Color(0xFF2D330D),
        tertiaryContainer = Color(0xFF444A22),
        onTertiaryContainer = Color(0xFFE0E7B1),
        background = Color(0xFF19120C),
        onBackground = Color(0xFFEFE0D6),
        surface = Color(0xFF19120C),
        onSurface = Color(0xFFEFE0D6),
        surfaceVariant = Color(0xFF51443B),
        onSurfaceVariant = Color(0xFFD6C3B6),
        inverseSurface = Color(0xFFEFE0D6),
        inverseOnSurface = Color(0xFF382F28),
        outline = Color(0xFF9E8E82),
        outlineVariant = Color(0xFF51443B),
        surfaceContainerLowest = Color(0xFF140D08),
        surfaceContainerLow = Color(0xFF221A14),
        surfaceContainer = Color(0xFF261E18),
        surfaceContainerHigh = Color(0xFF312822),
        surfaceContainerHighest = Color(0xFF3C332C),
    )
}

/** Green: Solo's green felt palette. */
internal object GreenColors {
    val light = lightColorScheme(
        primary = Color(0xFF1E6A4F),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFA8F2CF),
        onPrimaryContainer = Color(0xFF002115),
        inversePrimary = Color(0xFF8CD5B4),
        secondary = Color(0xFF4C6358),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFCEE9DA),
        onSecondaryContainer = Color(0xFF092017),
        tertiary = Color(0xFF3E6374),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFC2E8FC),
        onTertiaryContainer = Color(0xFF001F2A),
        background = Color(0xFFF5FBF6),
        onBackground = Color(0xFF171D1A),
        surface = Color(0xFFF5FBF6),
        onSurface = Color(0xFF171D1A),
        surfaceVariant = Color(0xFFDBE5DE),
        onSurfaceVariant = Color(0xFF404944),
        inverseSurface = Color(0xFF2C322F),
        inverseOnSurface = Color(0xFFECF2ED),
        outline = Color(0xFF707973),
        outlineVariant = Color(0xFFBFC9C2),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFEFF5F0),
        surfaceContainer = Color(0xFFE9EFEA),
        surfaceContainerHigh = Color(0xFFE4EAE5),
        surfaceContainerHighest = Color(0xFFDEE4DF),
    )

    val dark = darkColorScheme(
        primary = Color(0xFF8CD5B4),
        onPrimary = Color(0xFF003826),
        primaryContainer = Color(0xFF005139),
        onPrimaryContainer = Color(0xFFA8F2CF),
        inversePrimary = Color(0xFF1E6A4F),
        secondary = Color(0xFFB3CCBF),
        onSecondary = Color(0xFF1E352B),
        secondaryContainer = Color(0xFF354B41),
        onSecondaryContainer = Color(0xFFCEE9DA),
        tertiary = Color(0xFFA6CCDF),
        onTertiary = Color(0xFF0A3444),
        tertiaryContainer = Color(0xFF254B5C),
        onTertiaryContainer = Color(0xFFC2E8FC),
        background = Color(0xFF0F1512),
        onBackground = Color(0xFFDEE4DF),
        surface = Color(0xFF0F1512),
        onSurface = Color(0xFFDEE4DF),
        surfaceVariant = Color(0xFF404944),
        onSurfaceVariant = Color(0xFFBFC9C2),
        inverseSurface = Color(0xFFDEE4DF),
        inverseOnSurface = Color(0xFF2C322F),
        outline = Color(0xFF89938D),
        outlineVariant = Color(0xFF404944),
        surfaceContainerLowest = Color(0xFF0A0F0D),
        surfaceContainerLow = Color(0xFF171D1A),
        surfaceContainer = Color(0xFF1B211E),
        surfaceContainerHigh = Color(0xFF252B28),
        surfaceContainerHighest = Color(0xFF303633),
    )
}
